### ISSUE TITLE
Commands don't run if the terminal is closed

### ISSUE THREAD

**Issue by UziTech** [deepakgupta191199/vscode-save-commands#2]
If the terminal is killed after running a command running the command again does nothing.

**Comment by deepakgupta191199** [comment]
Can I know which version are you using ? I am unable to reproduce this issue in `0.1.0`

**Comment by UziTech** [comment]
It looks like v0.0.2 is the latest in openvsx https://open-vsx.org/extension/deepakgupta191199/save-commands

**Comment by UziTech** [comment]
V0.1.0 does fix this. Thanks
