### ISSUE TITLE
options for export/import saved commands across devices

### ISSUE THREAD

**Issue by valcaro87** [deepakgupta191199/vscode-save-commands#7]
i installed this extension in my desktop. i'm having hardtime how to export/import or maybe synchronize my saved commands to my laptop? TIA

**Comment by deepakgupta191199** [comment]
Can you give some more info ?
- What version of the extension are you using ?
- Are you logged in with the same account on both laptop and desktop
- Did you try running Settings Sync ?

**Comment by valcaro87** [comment]
- current version: 0.2.0 (both laptop and desktop) 
- yes login the same account(github)
- done installing 'settings sync' and everything was sync(latest gist file) except for this plugin 'save commands'

anything i missed? Thanks

**Comment by deepakgupta191199** [comment]
Sorry I am not able to replicate the issue. Can you do `Ctrl + Shift + P` and type `Show Synced Data`. Compare the diff of `Sync Activity` (especially Extensions) in both devices.

**Comment by valcaro87** [comment]
@deepakgupta191199 -  it is already synced. i am working on different projects(and saved workspaces), it worked by activating:
- Enable (Workspace)
- Add from workspace recommendations
- Sync this extension

thanks a lot!
