### ISSUE TITLE
"Delete global command" hidden in dark mode + no confirmation option

### ISSUE THREAD

**Issue by MaxDesignFR** [deepakgupta191199/vscode-save-commands#8]
Hi,

I unfortunately deleted all my saved commands in one missclick, as there's no way to confirm or revert this action. I also clicked this button accidentaly, not thinking it was a delete button (it is quite hard to see the icon in dark mode - see picture bellow).

![n7woJqwj4X](https://user-images.githubusercontent.com/46461193/188275241-3016fb73-17b5-4fae-9e94-5bb08f1eeeca.png)

**Comment by deepakgupta191199** [comment]
Sorry for that, I will surely add a confirmation dialog. If what you deleted was `Global Commands` then hopefully you can recover it by: 
- Press `Ctrl + Shift + P`
- Type `Show Synced Data` 
- Go to the diff where you can see your delete commands and recover it
